[package]
name = "project"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
eframe = "0.31.1"
egui = "0.31.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
